#!/usr/bin/env python

import requests
import json
import time
import csv

# Ask user for the affiliate ID and the API key of the company asking for commission deletion
aff_id = str(input("Enter affiliate ID: "))
api_secret = str(input("Enter API secret: "))

# Initialize URL request variables
parameters = (("affiliate_id", aff_id), ("state","paid"), ("limit", 50))
api_key = (api_secret,"")

# Get the list of commissions with a paid state for the affiliate to be deleted,
# then write an output JSON file to keep as a log. 
response = requests.get("https://api.getrewardful.com/v1/commissions", params=parameters, auth=api_key)
json_data = response.json()

with open(str(aff_id)+"_comm_data.json", 'w+') as output:
    dataformat = json.dumps(json_data, indent=2)
    output.write(dataformat)
    
output.close()

print("Commission list JSON file created.")

# Open the output JSON file in order to parse the commission IDs
commission_id = []
with open("comm_data.json", "r") as file:
    data = json.load(file)
    for data_dict in data['data']:
        commission_id.append(data_dict['id'])

# Initialize the list variable for logging of deleted commissions and
# count variable to see how many commissions were deleted
delete_response = []
delete_count = 0

# Iterate through the list of commission IDs and delete them one by one.
for commission in commission_id:
    delete_request = requests.delete("https://api.getrewardful.com/v1/commissions/" + commission, auth=api_key)
    delete_json = delete_request.json()
    delete_response.append(delete_json)
    delete_count += 1
    print("Commission with ID {} has been deleted".format(commission))
    time.sleep(30)

# Write delete log in a file (output is a JSON file)
with open(str(aff_id)+"_delete_request_log.json", "w+") as output:
    del_data_format = json.dumps(delete_response, indent=2)
    output.write(del_data_format)

output.close()

print("Delete JSON file created")
print("Total of {} commissions were deleted.".format(delete_count))
