#!/usr/bin/env python

import requests
import json
import csv
import time


# Ask user for the company name and the API secret of the company asking for payout details
company_name = input(str("Enter company name: "))
api_secret = input(str("Enter API secret: "))
page_number = int(input("Enter page number: "))

# Initialize URL request variables
parameters = (("expand", "affiliate"), ("state[]", "paid"), ("page", page_number), ("limit", 100))

api_key = (api_secret, "")

# Get the list of payout according to the status then write an output JSON file to keep as a log.
response = requests.get("https://api.getrewardful.com/v1/payouts", params=parameters, auth=api_key)
json_data = response.json()

with open(str(company_name) + "_payouts_data.json", 'w+') as output:
    dataformat = json.dumps(json_data, indent=2)
    output.write(dataformat)

output.close()

print("Referral list JSON file created")

# Open JSON file
with open(company_name + "_payouts_data.json", encoding="utf-8") as json_file:
    output_data = json.load(json_file)

# Create an empty list that would catch the dictionaries of each payout data
payout_output = []

# Load the json data in variable
payout_data = output_data["data"]

# Iterate through the JSON variable and add them on a dictionary and append them to the empty list
for data in payout_data:
    affiliate = dict(payout_id = data["id"],
                     paid_at = data["paid_at"],
                     amount_paid_in_cents = data["amount"],
                     affiliate_id = data["affiliate"]["id"],
                     affiliate_first_name = data["affiliate"]["first_name"],
                     affiliate_last_name = data["affiliate"]["last_name"],
                     affiliate_email = data["affiliate"]["email"],
                     paypal_email = data["affiliate"]["paypal_email"],
                     )
    payout_output.append(affiliate)

# Generate the keys of each dictionary
payout_keys = payout_output[0].keys()

# Write the list of dictionaries into a CSV file
with open(company_name + "-payout-data.csv", "a", encoding="utf-8", newline="") as output_csv:
    dict_writer = csv.DictWriter(output_csv, payout_keys)
    dict_writer.writeheader()
    dict_writer.writerows(payout_output)

output_csv.close()

print("Payout data page " + str(page_number) + " added to CSV file.")
